volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/workspaces:cached 
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - app-network
    working_dir: /workspaces

    command: go run ./app/main.go

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      # Ensure that the variables in .env match the same variables in devcontainer.json
      - .env
    ports:
      - 5432:5432
    networks:
      - app-network

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
